= 10 legal issues that consultants should know about

* October 8, 2010
* By Calvin Sun

As a consultant, you face more than technical challenges.
You face legal ones as well.
For this reason, the more you know about these legal matters, the less chance you have of getting into trouble.
Although this article is not meant as legal advice, it can help you be aware of some issues that concern you.
At the very least, it will alert you to questions and issues you might need to raise with your own attorney.

== 1 Status—consultant or employee?

Make sure of your legal relationship to your client.
Are you really an independent contractor, so you should receive a form 1099 at the end of the year reflecting your billings? Or could you actually be considered an employee, who should receive a form W-2?

The company using your services most likely prefers the former, and you might also.
The Internal Revenue Service in the past used a series of 20 questions to determine whether a person was a contractor or an employee.
However, the IRS recently streamlined those questions into a three general categories:

* Behavioral control (i.e., how much direction and control the business has over the individual, in terms of working hours, sequence of actions, and tools and equipment to be used)
* Financial control (i.e., how the individual is paid, e.g., weekly or hourly vs. a flat fee) 
* Type of relationship (i.e., how permanent it is and how the parties view the relationship)

Generally speaking, the greater the behavioral control, and the greater the financial control, and the more permanent the relationship is, the greater the chance that the IRS will view you as an employee rather than as an independent contractor.

== 2 Income and self employment taxes

The distinction between employee and independent contractor will affect the way you handle your taxes.
As an employee, your employer is responsible for withholding income taxes from your paycheck.
In addition, you and your employer each contributes half to Social Security payments.

If, however, you are an independent contractor, you are responsible for your own taxes because the organization that pays you generally will not withhold anything.
You're also responsible, depending on how you're organized legally, for completing appropriate business tax returns, such as a Schedule C , if you're a sole proprietor.

== 3 Sales tax on your fees?

Check with your state's department of revenue to see whether the fees you charge clients are subject to tax.
If they are, and you are not collecting and remitting such taxes, you could have a problem.

== 4 Intellectual property / "work made for hire"

In the course of your consulting work, you may create intellectual property for use by your clients.
Such work might be entitled to copyright protection.
In this case, be clear with your client about such copyright ownership.
You do not want your work to be considered a "work made for hire." The copyright for such a work would reside with your client, even though you were the one to create the work.

The client has high hurdles to overcome to claim work made for hire status—but be safe and avoid misunderstanding.
In your statement of work or in your contract, consider including a clause that expressly excludes your work product from being classified as a work made for hire. 

== 5 Nonexclusive vs. exclusive license

If you are the copyright holder of intellectual property, you can permit others to use that property via a license.
In return, of course, you probably would charge the other party a fee, or royalty, for the privilege of holding this license.

When you grant licensing rights, you can do so exclusively (to only one license holder) or nonexclusively (to more than one license holder).
You would do an exclusive license, in most cases, because your client asked or demanded it.
In such a situation, obviously, you would probably want to charge a higher royalty for an exclusive license than a nonexclusive license.

== 6 Professional liability vs. general liability insurance

You should consider at least two types of insurance: professional liability and general liability insurance.
While both protect you from things you do or fail to do, the specific focus of each is different.
Professional liability insurance (also known as errors and omissions insurance) protects you from the consequences of bad decisions and actions with respect to your consulting.
For example, if your improper systems implementation caused the client's business to shut down, resulting in loss of revenue, your professional liability policy might protect you from a client lawsuit.

General liability insurance protects you from other liability.
For example, such a policy might protect you in the event that your client falls within your office or you accidentally spill hot coffee over an audience member at one of your presentations.

== 7 "Claims made" vs. "occurrence" insurance coverage

Liability insurance usually differs from other insurance, such as automobile, in one important respect: Policies of the former are generally based on "claims made," while those of the latter are based on "occurrence."

Suppose you are involved in an incident on June 1, while you hold an insurance policy with company A.
On July 1, you change from insurance company A to insurance company B.
Then, on August 1, the other person files a claim regarding the incident.
If both policies were "occurrence" policies, company A would be responsible for this claim, even though it no longer carries your insurance.
However, if both policies were "claims made" policies, company B would be responsible, even though the incident occurred prior to your becoming their policyholder. 

== 8 Business organization option—the sole proprietorship

The way you organize your business determines the amount of reporting you do as well as the amount of legal protection you have.
If you are in business by yourself, the simplest form of organization is the sole proprietorship.
In Pennsylvania, in fact, if you include your name as part of your business name (e.g., you are John Smith and your business is John Smith Consulting), you don't even need to register with the state.
But if the sole proprietorship business name does not include your name, you would need to file a "fictitious name registration." Such a filing is designed to protect the public so that they know who is involved with a particular business.

While a sole proprietor provides for ease of tax reporting, it involves legal risk.
If you are sued because of your business, you have no legal way to shield your personal assets—they can be used to satisfy a judgment against you.
Consider this fact carefully if you choose a sole proprietorship.

== 9 Business organization option—the corporation

A corporation offers significantly more legal protection.
If you are sued over acts of your corporation, generally only the assets of that corporation can be used in a judgment.
Your own personal assets, if separate from the corporation, usually can't be used.
However, a corporation requires its own set of tax returns and typically requires formal meetings and documentation of those meetings.

To form a corporation, you'll probably need to file articles of incorporation with your state and you'll likely need officers, a board of directors, and bylaws.
For further information, check with your state's Department of State (not to be confused with the U.S.
Department of State).

== 10 Business organization option—the limited liability company (LLC)

A third form of organization, available in many states, is that of a limited liability company (LLC).
Think of an LLC as combining the best features of a sole proprietorship and a corporation.
On the one hand, the LLC does not file its own returns—you include income on your own Schedule C, just as for a sole proprietorship.
On the other hand, if you're sued, only the assets of the LLC are generally at risk—not your own personal assets.
For this reason, many consultants use an LLC form of organization.

*Calvin Sun is an attorney who writes about technology and legal issues for TechRepublic.
You can reach him at csun@calvinsun.com.*