= 10 things you can do to keep your IT job from taking over your life

* Version 1.0
* September 17, 2007
* By Jody Gilbert

IT professionals don't hold a monopoly on working excessively long hours or having job responsibilities cast a shadow over their personal lives.
But for many reasons, it's a field that invites long hours, persistent worries, and a reluctance—or inability—to mentally clock out when the workday should be over.
Some IT pros are all-but-indentured to a company that expects 24/7 availability.
Some face a staggering gap between resources and work to be done.
Others discover that effective time management is out of reach because of project volatility and constantly changing priorities.

For those trying to rein in their runaway professional lives, it doesn't help that "You won't be able to reach me" has lost its power.
Cell phones, PDAs, and remote access tools have all but eliminated the refuge of inaccessibility.
They might make your job easier, but they also make your job omnipresent.

All of these factors play into the phenomenon we call the *pervasive workplace*—when your job seems to permeate every corner of your life.

Discussion threads abound with horror stories of oppressive company regimes that keep IT pros stretched impossibly thin, pager-enslaved, and fearful of retribution (i.e., no more job) if they don't live to fulfill the organization's tech needs.
If you're stuck working for a company like that—and assuming that's not your ideal state—it could be time to hit the job boards.
On the other hand, you may be working for a great outfit that has enabled you to maintain perfect work-life balance.
But if you're somewhere in between, wishing you could scale back your work obligations to make a little more room for your personal life, here are a few ways to help keep the workplace at bay.

== 1 Learn to dismiss or delegate

Managing your workload is one key to preventing chores from spilling over into your personal time.
If your to-do list is busting at the seams and adding countless hours to your workweek, you have a couple of choices.
One possibility is to toss a few things overboard.
Maybe they'll drift back.
But if you carefully choose what to jettison, those things may not resurface for a long time—if ever.
Candidates for dismissal include things in the "It would be nice to..." category—tasks that aren't critical to daily operations or maintaining a secure and stable environment.
("It would be nice to update the company intranet to include end user resources...
but it can wait.")

Another possibility is to delegate tasks when you can.
This can be tough—especially if it's work you would have enjoyed doing if you had time or if you assume no one can handle the job as well as you could.
But if you're swamped, you need help.
And there are benefits beyond lightening your workload.
For one thing, you'll break the habit of hanging onto everything until you can see to it personally (which may never happen).
For another, you'll be helping co-workers or subordinates expand their knowledge and skills, making them more valuable to the company (and happily, to you as well).

We're not talking here about dumping a bunch of work on some poor hapless associate.
There's some upfront effort involved in selecting the best tasks to delegate, finding the best person to handle the tasks, and making sure that person has what's needed to get the job done.
But it should become an automatic part of your thinking when you're thinking, "How can I get all this done?"

== 2 Prioritize like crazy

This one goes hand in hand with the previous strategy: To make realistic decisions about what to dismiss or delegate, you have to be able to determine which items are critical (vs.
trivial or even unnecessary) and what's needed to execute on them.
The more experienced you are, and the more familiar you are with your organization's technology and business processes, the easier it will be to target the essential tasks on your list.
But you may still find it helpful to develop a set of questions to help you figure out what has to get done and what can slide.
It's a good analytical discipline to develop and it will remind you to step back occasionally instead of just allowing yourself to get swept up in an endless succession of chores.

Here are some questions to help with the triage process:

* What will happen if this doesn't get done this week (month, quarter, year)? Who will be affected?
* Are there dependencies that make it vital to complete this task?
* Can you do part of the project now and defer the rest until you have more resources?
* Can you permanently reduce the scope of the task or project or implement a simpler solution?

You may need to talk to a lot of people to make your determination, but that's actually a good thing—someone may come up with a perfect alternative you'd never considered (or volunteer to help).

== 3 Cross-train and document

Make sure you aren't indispensable.
If no one is equipped to cover for you during your vacation, what kind of vacation do you think you're going to have? You'll be checking e-mail, fielding questions, and putting in an extra week's worth of work before you leave and after you get back.
If you're a manager, you need a lieutenant—someone who understands the processes, projects, and relationships you handle, even though it's likely to be at a superficial level.
That person can keep an eye on the day-to-day concerns while you're gone (whether you're on vacation, attending a conference, dealing with a crisis, or consumed with a full-time project) and worst-case, he or she can escalate matters to your attention or to someone at your level or above.

If you're not a manager, you may be able to spread your knowledge and expertise by showing co-workers specific aspects of your job and parceling out your chores.
Your colleagues should be doing this as well.
In fact, a good manager will make sure your team operates this way, providing opportunities to cross-train and sub for each other in appropriate aspects of your work.

If you don't have time to train someone to fill your shoes, or even a small portion of one shoe, documentation can help.
Nothing elaborate—a checklist ("I have to do these nine things before leaving on Fridays"), a cheat sheet ("I follow these steps to double-check backups for the accounting database"), or a simple walk-through of a certain configuration procedure, maybe with screen shots inserted (however sloppily) in a Word doc.

== 4 Don't overpromise

It's natural to want to look unassailable in our ability to give customers, co-workers, and bosses whatever they ask for.
Sometimes, even an outrageous request seems doable because saying, "I can't get that much done by then" sounds so lame.
Don’t fall into this trap.
If you're a seasoned project manager, you know how to make a realistic estimate and establish a work plan that reflects what's feasible, even given setbacks.
But most of us are sitting ducks for misjudging our bandwidth.

No matter how hard it is, try to assume that everything is going to take longer than you think and that there will be obstacles that slow you down.
Give yourself wiggle room on your commitments.
("I'll try to get this done by next week, unless I get pulled into the final phase of UA testing.
If that happens, I'll let you know.") Of course, not everyone is driven to meet their deadlines and fulfill their promises.
But those folks probably don't have a big pervasive workplace problem anyway.
The rest of us need to be careful here.

== 5 Nail down expectations before you take a job—or take corrective action

Do your clients or company management expect you to be available 24 hours a day? If you accepted a job knowing that would be the deal, you can either live with your commitment, try to renegotiate the arrangement, or quit altogether.
But if you didn't sign on for that kind of availability, you'll need to take steps to redirect the terms of your employment.

First, make sure the boundaries are in place.
You might tell consulting clients something along the lines of, "You can contact me between 8:00 AM and 6:00 PM.
I may pick up messages outside those hours, but I can't guarantee it." Or you might tell your manager, "When I was hired, we agreed on some overtime for special projects, but nothing was said about 24/7 availability.
That schedule isn't going to work for me." Obviously, this may be a difficult conversation to have, and there could be negative fallout.
But if your situation is becoming untenable—your work is eclipsing your personal life and driving your stress levels off the charts—you have to be resolute, honest, and clear in what you're willing to commit to.

Once you make your case, you'll need to stick to your guns.
It's likely that you'll be asked to make special concessions at some point (maybe on a regular basis).
You can bend your rules where it seems appropriate, but be aware of the effect on the boundaries you're trying to establish.
For your own sanity, sometimes No is going to have to mean No.

== 6 Implement a rotation to cover special projects and to staff after-hours duties

Because IT usually re quires full-time monitoring and crisis response, as well as entailing work at odd hours to avoid disruptions during business hours, staff scheduling requires extra attention to make sure the burden is distributed reasonably.
Things may get crazy periodically and require bursts of overtime—that comes with the territory.
But if you're routinely asked to pull all-nighters and work all weekend on top of your regular hours, something's gotta give.

Most tech managers are well aware that driving their staff to the brink of burnout and beyond is not the way to establish a smooth-running, productive operation.
So if you bring the situation to their attention, it's likely that they'll try to work with you to help ease your schedule and build in a decent amount of downtime for you.
Does this work for everybody? Nah.
There are some stinkers out there who will dismiss your most reasonable request as lack of initiative.
But if you approach the conversation with some possible solutions in hand, you may be surprised at the results.

What kind of solutions can you bring to the table? Maybe you can get together with your co-workers and hammer out a rough schedule that spells out a rotation for weekend coverage, a tag-team approach for next weekend's server room relocation, and a comp day for each person the following month.
Maybe you can make the case for an intern to be brought in and then take over the responsibility for hiring and training that person to cover some of the routine tasks that keep you working late most evenings.
Maybe you can offer a more efficient plan for handling a major deployment that will mean that nobody has to work all night Friday.

== 7 Don't telecommute unless you're very good at compartmentalizing

Accessibility is a double-edged sword.
No one can argue that being able to handle some of your IT tasks remotely rather than being forced to drive to the office in the middle of the night is a step in the right direction.
But if you routinely do all or most of your work from home, you should be alert to the possibility of work seeping into various aspects of your home life.

There's no shortage of resources available offering pointers for effectively managing your telecommuting environment and practices.
One key recommendation is to make a clear separation between work and non-work so that you can focus steadily and productively on job-related activities and then turn them off, disengage, and be fully present in your home life.
As a telecommuter myself, I'm especially amused by one prescription that suggests you should dress for the office, get in your car, drive around the block, and return to your house as though you were arriving at work.
But as extreme as that gimmick appears, the objective is valid.

If your work is sitting in the next room and there's something you'd really like to finish, you may find yourself saying no to Frisbee with your kids after supper so that you can knock out that task.
"It'll just take a minute" becomes another lost evening.

Maybe you don't want to stage a phony drive to the office to put yourself in work mode.
But unless you want your job to infiltrate your personal life—with potentially destructive consequences—you should consider adopting these tactics:

* Set up a dedicated area for working.
* Establish a work schedule and stick to it.
* Take breaks just as you would in an office environment.
* When it's quitting time, quit.

== 8 Help users become more self sufficient

If you're be ing run ragged by users paging you at all hours, one solution is to try to educate th em to handle some situations on their own.
Teaching people how to do their own basic troubleshooting will improve their efficiency and decrease your support time and after-hours calls.
The most efficient way to handle this education may be to put together a series of tips as HTML pages, organized by category so users can find the information they need quickly without having to scan a whole list.
You can publish the tips on your internal network and provide a shortcut to them on users' desktops or push them to their machines.
Alternatively, you can burn the documents onto CDs and distribute them or simply print them out, although that makes updating the information more
cumbersome.

It's also helpful to make sure users understand when it's appropriate to use the after-hours pager and when it’s not.
This can best be accomplished with some written guidelines distributed in a handout.
If you send out a regular IT department bulletin or newsletter, this information can be featured prominently as a reminder.

== 9 Build in real downtime (and disconnect yourself)

You've probably heard reports citing statistics on all that unused vacation time— and how detrimental it is for worker health, productivity, and emotional well being to work without taking a break here and there.
Yet time off may seem like a total impossibility, with projects stacked up as far as you can see, staff shortages, or business upheavals requiring all hands on deck.
Nevertheless, you need to carve out some vacation time periodically.
You'll be vastly better equipped to wade back into the fray and to take on fresh challenges once you've recharged your batteries.
And don't vacation by sitting at home reading e-mails and fretting that you aren't at work as myriad problems accumulate.
DO NOT check your work e-mail when you're on your own time.
Make sure all your clients, bosses, co-workers, and partners know that you're on vacation and unavailable.
No IMs, no cell phone calls, no pages, nothing.

== 10 Invest time and energy in building your personal life

Some people are truly passionate about the work they do and seem content to devote themselves to it single-mindedly.
But most of us are likely to get a little sick of our work, even the aspects we truly enjoy, if that's the only thing we have going on.
It's important to have a life outside work, something satisfying and engaging, whether it's a sport, a hobby, social activities, or family relationships.
Maybe you do have those things.
If so, you're done here.
But if you're drained and uninspired and bored when you get home from work, it's time to shift gears.
You need something to look forward to after work so that you can put work out of your thoughts for a while.
That's a good thing.