= 10+ things you can do to avoid ethical breaches

* By Calvin Sun October 12, 2011, 11:16 AM PDT
* Takeaway: If you’re headed toward an ethical quagmire, a few basic steps can help you find your way back to the high ground.

Enron...
Worldcom...
Something-gate...
Hardly a day goes by without news of someone or some company in trouble because of ethical issues.
For the good of the organization, and for the good of your own career, it’s important to avoid ethical issues — and conversely, to act ethically.
Here are some things to consider in this regard.
The first two items are directed at the leadership of an organization, while the rest pertain to everyone.

Note: This article does not constitute legal advice.

== 1: Have a code of conduct

Your staff will have an easier time handling ethical issues if they have guidelines to follow.
Of course, no written code can cover every single situation.
Nonetheless, establishing principles — and the consequences for failure to act ethically — will help your staff.
When establishing a code of conduct, keep in mind the 80/20 rule.
That is, focus on the possibly small number of issues that seem to occur the most often.

== 2: Model the behavior you wish to see

____
*A fish rots from the head down.* — Old saying
____

For better or for worse, your staff will watch how you act and will act the same way.
If what you say is different from what you do, your staff will focus on the latter and ignore the former.
If you want your staff to act ethically, do so yourself.
If you have established a code of conduct, make sure you yourself live up to it.

== 3: Disclose any conflicts of interest

As an employee of an organization, your decisions or actions should advance the interests of that organization.
At times, though, you might be in a position where your decision might affect your own interests as well.
Suppose you are part of a group that is deciding on a supplier, and one candidate is a company owned by your brother.
Now, that supplier might turn out to be the best qualified one.
However, to avoid any appearance of impropriety, you probably should disclose the nature of your relationship to the company.

== 4: Recuse yourself

Another option, in the case of a conflict of interest, is to recuse yourself.
You could consider abstaining from any decisions regarding that supplier, after explaining why.
Be aware that the group, once it learns of the conflict, might still want you to be involved at least in discussions, if not the decision.
Other times, the group might wish you to have no part at all, either discussion OR decision.

== 5: Get consent

Not all conflicts are show stoppers.
Maybe your interest in that supplier really isn’t that big a deal.
Whatever else the reason might be, you might be able to participate if, in addition to disclosing the conflict, you get the consent of other key people.

== 6: Find an alternate method

Suppose your boss or a co-worker is asking you to cut corners on a particular procedure.
You believe that the requested action presents an ethical problem.
You are reluctant to take this action, but at the same time you believe your career may be harmed if you refuse.
In this case, try to think beyond the two choices of accede and refuse.
Try to come up with a third alternative that meets the other person’s objective while still remaining ethical.

== 7: Avoid the issue or question

____
Ask me no questions and I’ll tell you no lies. — Old saying
____


One alternative method is to avoid lying by avoiding the question in the first place.
I am not saying to go through life or your career this way, but sometimes this approach is appropriate.

While studying the Titanic disaster, I came across another person whose specialty is collecting and posting (morbid as it sounds) death certificates of passengers.
Having seen such certificates of Pennsylvania passengers, and knowing that the official request form limited requests to those from relatives, I asked him once how he was able to obtain these certificates.
His answer? He avoided using the request form and instead sent his request via his own letter, along with his fee.
That letter never mentioned whether he was a relative — that is, the letter contained no lies.
Even though he avoided the official form, he told me that he still was successful most of the time.

== 8: Focus on the issue, not the person

If your boss or co-worker does ask you to cut corners, and you have concerns over the ethical implications of doing so, avoid moralizing.
You don’t need to say or imply that the other person is dishonest or unethical, even if you think so.
Alienating the other person will only make the situation worse.
Instead, focus on the issue itself and on why the requested action will pose a problem.


== 9: Stress the advantages of the ethical approach

For example, instead of simply criticizing the other person, come up with credible reasons why your ethical approach is the better one.
For example, perhaps both you and the other person will keep your jobs...
or stay out of jail.
Try to see the bigger picture and look from that other person’s perspective.
Think of ways your approach helps that person more than the unethical approach does.


== 10: Document key matters

Obviously, documentation of key matters is critical in these situations.
Make a note, via memo or email, of all disclosures you made regarding conflicts, any consent from other people, and any concerns you have about potential unethical approaches.

== 11: Blow the whistle

I put this point last for a reason.
Blowing the whistle to a government agency, or to the news media, probably should be the last step you take.
It should be your last resort, to be done only if the above steps all fail.
Yes, you might be protected by state or federal whistleblower statutes, which might forbid your being terminated or give you the right to sue.
However, blowing the whistle could still subject you to being ostracized by friends, co-workers, or even family.
You also might have trouble later finding work.
In other words, before taking such action, count the cost carefully.

In addition, consider consulting an attorney who represents plaintiffs (employees or ex-employees) in employment cases and who knows about whistleblower statutes.

== Other steps?
Have you ever been caught in an ethical dilemma? What steps did you take to resolve it?

About Calvin Sun

Calvin Sun is an attorney who writes about technology and legal issues for TechRepublic.