= Comparison between MTA's (Postfix vs exim vs sendmail)

If discussing the internet so kind of program or software are there but when come on message handling services so mail transfer agent is an application that transfers information from one PC to another using client–server application architecture. *MTA* responsible for both the side client and server part of the *SMTP* (Simple Mail Transfer Protocol).

A mail server is your personal PC that serves as an electronic post office for email. Mail exchanged across networks is passed between email servers that run a specially designed application. These application programs are built around agreed-upon, standardized protocols for managing information. Here you are going to have the right information about the Postfix vs exim vs sendmail.

You have an option in using MTA in a Linux system. It can be used sendmail, postfix, qmail or exim. A selection of MTA relies on many aspects such as followings

* A good protection record
* Efficiency with good performance on high load
* Versatile and clear understandable files
* Connect to data source in many formats
* Many of the SMTP versions in use
* Quality documentation of third-party is available
* There are important customer communities

== Exim

Exim is mail transfer agent (MTA) used on Unix operating-system. Exim is free software application allocated under the GNU Common Public Certificate, and it is designed to be a standard and versatile mailer with comprehensive features for verifying incoming e-mail.

A great number of Exim setups are available, especially within the ISP and colleges and universities in the UK.

* Security purpose: Quite good
* Performance Level: Very good
* Since: 1995.
* Community: Large
* Guides are available for settings, Not very easy to set up because it simply upgrades the Unix email program idea. But the most significant factor is this application is not managed and moreover it is not purely an open source solution. Exim’s protection has had a number of serious protection issues clinically diagnosed over the years.

== Postfix

Postfix is like qmail but the interface is like Unix so simple to set up. postfix rests between qmail and exim. Postfix is less flexible than Exim, and this is mostly due to its major style requirements being protection. Individually in really like postfix.

* Security purpose: Good record.
* Performance Level: Excellent
* Since: 1997
* Community: Medium-sized
* Postfix is a no cost and open-source mail transfer agent that tracks and provides an email. Postfix is launched under the IBM Public Certificate 1.0 which is a no cost application license. Originally published in 1997 by the IBM.

== Sendmail

Now the term to know about the sendmail. Sendmail is charged with many protection problems in previous. Now it's a bit enhanced. Sendmail delivered as standard MTA is many a Linux system. It's simple to set up and appropriate environment where protection is not the main concern. Sendmail is most well known MTA.

* Security purpose: Not better but still better from the past all versions
* Performance Level: Ok for many
* Since: 1982
* Community: Large
* Sendmail is a general purpose internetwork email redirecting facility that facilitates many kinds of mail-transfer and delivery methods, including the SMTP.
