version: '2'

services:
    drone-server:
        image: drone/drone:0.7
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=${DRONE_HOST}
            - DRONE_GOGS=true
            - DRONE_GOGS_URL=http://git.preeper.org
            - DRONE_GOGS_SKIP_VERIFY=false
            - DRONE_SECRET=db9a08bb-29ab-45d3-8cec-46bb8164a66f

    drone-agent:
        image: drone/agent:0.7
        command: agent
        restart: always
        depends_on:
            - drone-server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=ws://drone-server:8000/ws/broker
            - DRONE_SECRET=db9a08bb-29ab-45d3-8cec-46bb8164a66f
