= Efficient metrics: Be careful what you measure

* March 7, 2011
* By Alan Norton

Every company larger than the mom-and-pop store on the corner has them—dozens upon dozens of reports, charts, and performance metrics. How accurately they tell the story of a department's performance and the company's overall performance is critical to everyday decision making and to those all-important course corrections on the road to success. Unfortunately, metrics can be misleading—especially at the department level. In this white paper, I will identify where and why metrics can present bad or ambiguous information and what can be done to minimize this problem. 

== Performance metrics at the department level

The theory of departmental reporting is simple. Each department meets its own goals and shows improvement month to month, and these improvements roll up to a better bottom line for the company. But that is not how the real world works.

It is common for each department to have its own set of metrics that it reports on. What is measured may be chosen by the department managers; they know their business best, right? Worse yet, the data is most likely collected and compiled by their own staff.

Reporting metrics in this manner has its own set of inherent problems:

* Cost inefficiencies—Reporting costs may exceed actual or potential savings
* Self serving interests—Managers tailor the data and statistics to best show their performance
* Tunnel vision—Managers may report and make decisions based on their narrow set of metrics, occasionally at the expense of another department or their own unmeasured metrics
* Conflicts of interest—What is best for the department is not always best for the company
* Information overload —There may be a tendency to measure everything to get that warm and fuzzy feeling

Good managers will do whatever it takes to make their numbers look good, especially if incentives are tied to those numbers. Unfortunately, that may come at the expense of other company functions or employee morale. Eventually, this type of reporting negatively affects the corporate bottom line—and that is certainly not the intent of a good set of metrics.

The following scenarios show how the best intentions of managers and their metrics can go awry when viewed from a higher perspective.

== Case study: Corporation XYZ

**What**: XYZ produces and supplies electrical sub-assemblies for Aerospace companies

**Who**: Receiving/Inspection/Test (RIT) and production departments

=== Scenario 1

RIT is responsible for pre-tinning electrical components used in production. RIT's cost per item tinned is carefully tracked. To save money and lower their cost of tinning, the manager of RIT works with purchasing to order pre-tinned components directly from the suppliers. RIT's cost per item tinned drops dramatically, and the RIT manager is rewarded for his improved metrics.

However, production has experienced increasing problems with the quality of the tinned leads of the electrical components. Production rework is a closely watched metric and upper management wants to know why their rework and resultant manpower costs are on the rise.

Production points fingers at RIT for shoddy pre-tinning. RIT notes the money they are saving.

The costs incurred by production's rework far exceed the savings realized by the purchase of pre-tinned components. Should the RIT manager be reprimanded for improving the metrics he was charged to improve? This and other unintended consequences are possible when costs are measured at the department level and not in the aggregate. 

=== Scenario 2

Production is at risk of failing to produce the required 30 AV-103-B sub-assemblies due to a lack of critical components from suppliers. Failure to produce and deliver the 30 sub-assemblies by the end of the month would trigger a $150,000 penalty. There are seven days left in the production month. The critical components holding back the completion of the remaining AV-103-Bs are due in Friday afternoon.

RIT has been made aware of the incoming consignment and has committed to delivering the components to production by start of business on Monday. Supervisors have scrambled to line up the necessary manpower needed over the weekend to receive, inspect, test, and tin the critical components. 

RIT managers are paid quarterly bonuses for bringing their labor costs in under budget. The additional overtime expenses mean that there will be no bonuses this quarter. The RIT managers have made the right decision. Avoiding the $150,000 penalty is best for the corporate bottom line, but is it fair to penalize the RIT managers for doing the right thing?

Be careful before you tie incentives to departmental metrics. Bonuses tied to metrics collected at the departmental level can become disincentives—exactly the opposite of what was intended. 

== Exception reporting

Following an exception reporting strategy at lower, more discrete levels in the company can reduce the number of charts and reports a manager must review to efficiently run his or her department.

* Identify problems and potential problems in advance.
* Minimize the information a manager must routinely review.
* Measure quality, cost, and time but report only exceptions.
* Set reasonable exception parameters—not too wide to generate hundreds of exceptions and not too tight to miss potential problems. 

Figure 1: Focus on exception reporting at the discrete level and performance reporting at the aggregate level.

Figure 2: Production Metrics—It makes more sense to track the handful of parts and raw materials that currently are or may in the future affect production by using exception reports. Use performance reports predominantly at higher levels of production.

== What about financial metrics?

Clearly, traditional financial metrics are critical to keeping costs in line. Several strategies can be employed to help a manager wade through all those pages of financial numbers:

* Add charts—Charts can be added; for example, a pie chart can be added to show the labor cost overages by product line.
* Exception reporting can be used to show only those financial metrics outside predetermined parameters
* Highlighting can be used to quickly identify problems, possible problems, and exceptional performance:
> * Red highlighting for overages falling outside predetermined thresholds
> * Yellow highlighting for costs that are in danger of reaching problem levels
> * Green highlighting for budget under-runs

It is important to remember that financial metrics don't tell the whole story and, by themselves, they too can be misleading.

== Metrics should be customer-centric

Some of the so-called IT industry standard metrics have the wrong focus. For example, system uptime is
commonly used to measure the performance of critical IT systems. But what does 99.72% uptime mean to a
customer? Two hours of system downtime on Monday morning from 8:00 to 10:00 AM is very different from
downtime from 5:00 to 7:00 AM on a Sunday morning. A single uptime number is data, not information. From a
customer's point of view, they want to know how well their systems performed during working hours. Even
more information can be provided by breaking the downtime into scheduled and non-scheduled downtime. The
metrics used by IT and all other departments should be customer-centric and not department-centric.

== Efficient metrics

Here are some guidelines that can be used to reduce the amount of misleading information you generate and to improve the overall efficiency of your metrics:

* Measure performance at the aggregate higher levels.
* Measure exceptions at lower levels.
* Follow SMART techniques—metrics should be **S**pecific, **M**easureable, **A**ttainable, **R**elevant ,and **T**imely.
* Determine the cost of metrics and throw out reports that cost more than they save or might save.
* Manual data collection is expensive—automate, replace with a substitute, or eliminate altogether.
* Use departmental reports as guidelines only.
* Tie incentives to division or corporate bottom line not departmental metrics.
* Verify accuracy—no information is better than bad information.
* Avoid misleading or ambiguous information—bad decisions based on this kind of information can be difficult to identify and costly to correct.
* Use a third party to prepare metrics—if that is not optimal, create a division/corporate-level position that collects and reports metrics.

== In summary

The time-honored story of the blind men and an elephant is a good metaphor for how metrics can be misused. Each blind man felt a different part of the elephant and each came to a different conclusion as to what an elephant was like. The story warns us that seeing only part of the picture can be misleading. The elephant when viewed from one foot can be deceiving, just as the performance and health of a corporation when measured from lower levels can be misleading. Such metrics are only a snapshot of one small slice of the corporate picture. When viewed from far enough away, the elephant quickly becomes recognizable, just as the primary exception, a long trunk, immediately distinguishes the elephant from other animals.

As important as metrics are to an organization, all too often insufficient thought has gone into the development of a good, comprehensive metrics package. Investing a little time to improve what is reported and how it is reported will quickly pay dividends for any organization at all levels. Choose your metrics wisely—what you measure is what you get.