= Failing startup checklist: 4 signs it's time to pull the plug

* By Conner Forrest March 24, 2014, 4:00 AM PST // connerforrest
* Facing failure as an entreprenuer can be devastating. Here are four factors that can hel you figure out if you should close the casket on your startup.

No one thinks their own baby is ugly. When it comes to assessing the health of your startup, you will likely approach it with a bias. This is especially true when it comes to knowing when to admit defeat and pull the plug on your startup.

A big part of being a successful entrepreneur is not being afraid of failure. Often, though, the concept of not being afraid to fail is used to mask a refusal to believe that you can, indeed, actually fail. Failure is a terrifying concept but, thankfully, [it](http://www.techrepublic.com/article/the-dark-side-of-venture-capital-five-things-startups-need-to-know/) is not the end of the road for a top-rate entrepreneur. You can own up to your failures, but not be defined by them.

According to Brian Rich, a managing partner at Catalyst Investors, the most important aspect of a founder/investor relationship is transparency. If you see flashing lights, or have a feeling that your business is heading in the wrong direction, you have an obligation to bring it before your investors and mentors. Heading off a problem early can keep you from careening off a cliff.

Some problems are obvious, such as not being able to raise any more capital or running out of cash. Some problems, however, are not so apparent. Use these four factors to determine if it is time to put your startup to bed.

== 1. Bankrupt of passion

"If you don't absolutely love what you do, if you don't have a fire in your belly, it's time to throw in the towel. You can't fake passion when selling your vision to customers or to employees over the long-term. Every business needs & deserves a passionate leader who is willing to do "whatever it takes" to succeed," said Matt Mickiewicz, CEO & co-founder [Hired.com](https://hired.com/).

We've all heard the adage "love what you do and you'll never work a day in your life." For startup founders that should read, "love what you do and you'll work everyday of your life." When it comes to founding and running a startup, you're building your life around this crazy idea you have and you're going to do everything in your power to make it work.

Passion is a challenging thing to measure. Ask yourself why you are doing what you're doing; try to understand what your motivation is and that might point you to how much passion you have left. It may be difficult to tell when you have run out of passion, but it's essential to the future of your company that you get a read on that metric.

"If you have a demotivated CEO, you have a rudderless company," said Brian Rich, a managing partner at Catalyst
Investors.

Rich was quick to qualify that a loss of passion, alone, might not signal a need to shut your company down. Try taking some time off, gather your thoughts and take a deep breath. You should be able to figure out if you were just stuck too far down in the weeds for a season or if you are truly burned out. If you are burned out, try implementing a management shift to see if that changes the attitudes of your company's leadership.

== 2. Customers don't care

"The most common indicator that it’s time to fold is when the team is energized, the product is ready to ship, and there is no customer adoption. Of course, I want my companies to try different marketing strategies (multiple [strategies]), tweak the product (a lot), and anything else they can think of, but, after that, if the potential customers are still not interested in becoming real customers, it is time to fold or pivot into something completely new," said Tripp Jones of [August Capital](http://www.augustcap.com/) .

As I have [written before](http://www.techrepublic.com/article/startup-hiring-how-to-build-your-a-team/), one of the hardest truths for entrepreneurs to swallow is the fact that no one will ever love your idea as much as you do. But ultimately, you still need customers to fall in love with your product. You need evangelists.

"If your users and customers aren't in love with your product, and can live without it, and you don't have a clear and definitive product plan to fix it, it might be time to call it quits," Mickiewicz said.

To address this, do more market research on your competitors. Try to figure out when they started and how long it took them to gain traction. Every company's story will be different, but you should get a pretty good idea of what your timeline should look like. At some point you need to decide whether or not you believe customers will ever be turned into raving fans. 

== 3. Can't keep talent

If you can't get people to put up with you on a daily basis, that might be a personal problem. But, if you cannot attract and retain top talent, your startup might be on its deathbed. A big part of [hiring](http://www.techrepublic.com/article/startup-hiring-how-to-build-your-a-team/) is convincing
potential employees that your vision is the right one.

"If your vision isn't resonating with potential employees, and you are simply unable to hire and retain the level of talent that you need to succeed in the long-run, it's a big red flag that something is seriously broken," Mickiewicz said.

When it comes to attracting talent, you have to first ask yourself if it is a supply problem or demand problem. If it is a supply problem, meaning there aren't enough talented developers to go around, that might not be indicative of a problem with your specific startup. But, if it is a demand problem, meaning you aren't creating enough of an incentive to come work for you, that could be an issue.

For a startup to work, all employees must fully buy into the idea behind it. Talent retention can be difficult, especially in crowded markets like Silicon Valley and New York. If you haven't been able to get your employees to believe in your idea, it might not be the right idea.

== 4. Miscalculating the market

Founding a successful company takes a solid understanding of the market that company will play to. Sometimes, though, founders and investors can miscalculate how a company will be received by the market. When Brian Rich assesses the evolution of a portfolio company in the marketplace, he asks these three questions: 

1. When I go back and read my original investment thesis, is the market what I thought it was?
2. Is the market opportunity what I thought it was?"
3. Is the company unable to attain the market share that I thought it would.

If your competitors are outpacing you, then you start changing your strategy. If you are in a position to be acquired to get ahead, there is no shame in planning an exit strategy by acquisition. Obviously, that is not an option for all companies, but it should be considered by those it is possible for.

For an investor, it can be difficult to see a portfolio company failing. Especially if they made the initial investment and a follow-on investment, they are admitting that they were wrong. Regardless, it is a hard truth that needs to faced head-on and should be faced realistically. According to Jones, your investor should face that with you.

"Deciding to shut down your company is a brutal realization. Emotionally, it falls somewhere between a bad breakup and a death of a loved one. Not fun," Jones said. "Unless the company can be sold or the team can be acqui-hired, the founders are typically the last ones left to go down with the ship. A good VC should still be there next to the founders at the end." 