====== How to structure your startup as the company grows
By Conner Forrest | September 22, 2015, 5:58 AM PST

Often, startups overlook organizational structure until it's too late. Here are some considerations for founders as they grow their companies.

A lot of startups share the same mythical origin story — a couple close friends plotting and scheming in a basement or garage, trying to build a company that will change the world. But, if they're lucky, the story doesn't stop there.

As a company grows, it transitions from two founders to a team and moves out of the garage and into a real office. While this is an exciting transition and, usually, a positive sign, it is also the time that certain growing pains can begin to emerge.

One such problem that startups can run into is organization structure, or how a company defines roles, teams, and supervision. By carefully planning for that growth, startups can avoid some common headaches.

Here are considerations for startup founders as they strategize on organizational structure.

===== Defining roles

Early on in the life of a startup, founders will often fill as many roles as possible to save money and simply get the work done that's on the table. When a company is founded by more than one person, the multiple founders will often have complementary skillsets.

As important that it is that you're not stepping on each other's toes, you have to be open to change. Dave Sorin, a partner at McCarter and English (http://www.mccarter.com/) , recommends executives and founders revisit their roles from time to time to make sure that there are no "holes" present in the skillset needed to make your business successful.

"If the holes are significant and are impeding sales growth, capital raising or any other key component of your business, it's a sign that you need to bring on professionals who will fill those holes," Sorin.

Roles can be fluid, so it's important that founders don't lock themselves into a structure that
doesn't allow for shifts.

===== Architecting the structure

Once you have some leaders established, it is critical that you determine the remaining hierarchy (if there will be one) and how you'll delegate tasks. Then, you will need to establish a team structure and how those teams will be led.

Hrach Simonian of Canaan Partners (http://www.canaan.com/) offered the following recommendation: "Decide who oversees each department head at the C-level and avoid
managing by committee ever."

Different companies will have different needs as far as teams go, but it is important that founders consider how they want to structure their teams and how they want them to interact. For example, Twilio (https://www.twilio.com/) 's Roy Ng said the company relies heavily on small teams.

"Small teams allow for autonomy, rapid experimentation and innovation. Small teams have enabled Twilio's ability to grow and scale, and at the same time maintain the same level of passion, hunger, resourcefulness and productivity our founding team had on day one."

Nothing is set in stone, but founders should have an idea of the culture they want to build and how teams fit into or perpetuate that culture. Also, factor in the end goal when you are structuring your company.

"You will build differently if this is a lifestyle business that you intend to operate for income as opposed to selling the company at some point or undertaking a public offering," Sorin said.

===== Building your team

Obviously, you're not going to grow your team without hiring. As a founder or executive, it's important that you realize you can't do everything by yourself, Simonian said, but it's essential you involve yourself in the hiring process.

The first hires you make will be some of the most important hiring decisions you make. Your early hires will depend heavily on your business model and the market you're in, said Brad Peters, co-founder of Birst (https://www.birst.com/) .

In the early days of Birst, Peters and Paul Staelin were focused on selling to the financial services industry before broadening their offering to the greater enterprise.

"Because of this early focus, our first hires were salespeople who understood financial services inside and out, so we could scale the business past the first couple of customers we managed to win on our own," Peters said.

While founders should be as involved as possible in hiring, there's a point where you need to bring in someone to manage the process.

"If you're having trouble remembering everyone's last name in the company, you need a full-time in-house HR/talent head," Simonian said. That usually happens when you grow past 50 people.

===== Bring in the professionals

Once a company reaches a certain point, founders will need to consider talent to fill specific leadership roles in the company. One of the most important aspects of your business in this regard is legal.

"Quite possibly the first place you'll need to bring in advisors and professionals is anywhere in the organization that involves intellectual property, which is likely your greatest asset," Sorin said.

In addition to a defendable intellectual property, companies need money to keep growing. As you raise capital and have more money to account for, it's a good idea to bring in a financial professional. However, Simonian recommends avoiding hiring a CFO early on. Instead, he said. hire someone at the director or VP level and hire a CFO later on.

Additionally, as you seek to expand into new markets or further scale your existing opportunity, it may benefit you to hire experienced sales and marketing personnel, Sorin said.

===== Communicate with the board

A board of directors can be one of your greatest assets as a startup founder. As such, communication with the board is key. Don't wait for board meetings to ask advice or convey new information. The process doesn't have to be formal. Simonian said your communication should be "casual but frequent."

All of your advisors and peers can be helpful, but your board has a vested interest in your success and, hopefully, experience to back up their advice. Your board members have also likely been through the startup process before, maybe more than once, and can help you navigate the waters as you build your business.

Outside insight can be tremendously helpful, but remember that you, as a founder or executive, must be comfortable with the decisions being made as your organizational
structure takes shape.

"You should absolutely listen to your team, peers, advisors and supporters, but at the end of the day, the most important person you will have to answer to is yourself, so make sure you are in line with the decisions that are being made for your company," said Amanda Slavin, founder of CatalystCreativ (http://www.catalystcreativ.com/) .

