====== How to fund your startup without venture capital
By Conner Forrest June 1, 2015, 1:00 AM PST // connerforrest

Want to raise capital for your company without the help of VC or Angels? Here's the skinny on some alternative methods for funding your startup.

In virtually every instance, there is one ingredient that can make or break a startup in the early days -- money.

Many founders follow the same path. Once they have an idea, they begin pitching traditional VC firms or start looking for an angel investor. These options are great resources for some, but raising money this way can be problematic.

For starters, you usually have to give up equity shares to raise the money.

"My experience is that when you have outside funding, they're going to act like they own your business because they do," said Stacy Griggs, president and CEO of link:http://www.techrepublic.com/article/ip­targeting­startup­el­toro­disrupts­online­advertising­with­phonebook­for­the­web/[El Toro].

If you want to be able to make moves quickly, without much input, it makes sense to avoid traditional equity­based funding models. Also, as you continue raising money, it can contribute to dilution, which means you'll own less and less of your company over time.

Entrepreneurs who need cash, but want to avoid VC or Angel investments, actually have quite a few options for raising capital on their own terms.

Let's decode a few of the most popular alternative methods of fundraising.

===== Friends and family

It's often said that you should never go into business with family, but that doesn't mean you can't borrow money from them, right?

Many times it may be easier to convince your friends and family to invest in your startup than to convince an institutional investor. This carries its own connotation for your business, as the average layperson typically doesn't have the same eye for a disruptive company that a seasoned investor does. However, the support of friends and family can be a valuable asset when you are trying to get your startup off the ground.

"No one will love your ideas as much as your family," said Travis Fox, co­founder of 3Form Media. "They can share your belief in your vision or plan, and that kind of support has a value all its own."

Still, if you need money for your business it can be a smart place to look. The first reason being that there's much less song and dance involved in getting the investment and the funds are usually available quickly.

"We didn't have to spend a month writing a business plan, we could spend that month on figure out how to better perfect our technology," Griggs said.

Money and relationships can be a caustic mix, though. When someone invests a large sum of money in a project, they are often met with the desire to control part of it. According to Fox, this could lead to unwanted advice, a demand for progress updates, and miscommunication ­­ something that can especially dangerous when it's with people you know well.

Private equity and venture capitalists go into deals with the knowledge that they won't get everything back. It's not always like that with friends and family.

"Of course, the most dangerous possibility of this situation is if the venture fails," Fox said. "Very close, valuable personal relationships could be destroyed."

===== SBA loans

The link:https://www.sba.gov/[Small Business Administration] (SBA) is a government entity that provides assistance to small businesses in the US in a variety of ways, including various loans and grants. At the end of its fiscal year in 2014, the SBA approved nearly 53,000 loans totaling almost $20 billion.

The SBA works through regional offices. Their loan and grant programs are great ways to raise funds without diluting shares and they also offer mentorship programs. Griggs said that SCORE, which stands for services corps. of retired executives, is a great resource for startup mentors. They may not be in tech, specifically, but many have bootstrapped a company before.

"I would always encourage entrepreneurs to develop a relationship with the local SBA," Griggs said.

Generally you might pay a little higher interest rate with the SBA, and the money lending programs have their own parameters based on your business plan and your financial numbers.

"Government­sponsored programs often have very specific requirements," MacLeod said. "So you have to tailor your submission, and therefore how you run your business, to fit those requirements."

If you fit the requirements, though, the SBA can be a great option for fundraising and can end up as an advocate for you and your business. However, you will have to pay close attention to timing if you are planning on pursuing this route.

"Your main concern is the time to funding, which can take three to six months," Fox said. "If you are moving forward on a vision that involves some form of innovation, it can be difficult to step back and wait months for funding when the rest of the world is working to catch up"

===== Bootstrapping

If possible, one of the best ways to fund your startup is by bootstrapping with existing capital and revenue. El Toro started with a "Seed" round of friends and family, and supplemented their growth with revenue.

"Right now our growth is fed by our cash flow," Griggs said. "As we continue to grow, it produces more cash flow and we can reinvest that cash flow ­­ into additional servers, into additional people, those types of things."

Using revenue won't work for everyone, and it can be a risky play. If an investor gives you money without a second thought on return, you can scale quickly. However, relying on revenue can limit your growth, since you can only grow as fast as your revenue does.

The key to bootstrapping is the door that it opens once you have reached a certain size. Once your revenue hits a certain number, banks and traditional institutional investors will be more likely to lend to you.

"The market wants revenue, even if it's small," Fox said. "Take and keep more of your ownership, grow your financing by proving your idea is valuable. You may just find it easier than you think to find that angel investor."

===== Grants

One of the often overlooked sources of funding for new startups is government and private sector grants. Grants require no equity to obtain and they typically don't require that you pay them back.

The pros of grants are obvious, but there is a catch. According to link:http://wallhop.com/[Wal Hop] co-founder Rob Green, the process is a nightmare.

For a government grant, it starts with actually finding one, which can exist at different tiers of government, or within an offshoot government program. Once you find a grant and determine that the department has available funds, you must complete a long application process. Also, beware that many government grants only accept applications at certain times of the year.

"And don't think it stops once you've received your grant ­ depending on the program you may be required to check in with the issuing organization at certain check­marks to complete or file certain reports," Green said.

This seems like a lot of work, and it is, but that will probably scare off a lot of competition who aren't willing to put in the hours. Private sector grants are much easier to find, but typically a lot harder to get. Large corporations are often looking to give back as part of a corporate responsibility effort or to receive benefits of their own," Green said. "I'd recommend looking up some of the largest banks, insurance companies, and professional service groups to determine if they have any programs you're eligible for."

There is more competition, and sometimes more stringent requirements for revenue and growth, but private grants have their own set of advantages as well. Often times there is an award ceremony or gala which Green said be a great opportunity for networking and garnering press.

Finding money for your startup can be difficult, especially if you are pursuing it in an unorthodox manner. Hopefully these options will help you find some of the capital you need to get your business off the ground.