= Most employees waste 32 days of productivity per year on bad enterprise apps
By Conner Forrest | March 5, 2018, 8:12 AM PST 

A new report from RingCentral says some workers toggle between apps up to 10 times per hour.

* 69% of workers waste up to 32 days of productivity per year navigating through their communication apps. — RingCentral, 2018
* 68% of workers toggle between some 10 different apps per hour at work. — RingCentral, 2018

The massive number of enterprise apps that employees use on a daily basis is starting to kill productivity and cost companies money. According to a link:https://www.ringcentral.com/lp/future-digital-workplace.html[report] from RingCentral, 69% of workers waste up to an hour of productivity each day (or 32 days per year) just navigating their workplace communications apps.

That's more than an entire month of the year wasted on simply trying to find the right tool, or app, for the job. What's more is that 68% of workers in the report claimed to be switching between 10 different apps every hour at work.

For business and IT leaders, this may be a wake up call to consider a more minimal app strategy. Or, if a large number of apps is central to their business, they may need to rethink employee training and education.

Or, as noted by Larry Dignan of our sister site ZDNet, maybe this is just a sign that most enterprise apps aren't all that great.

Regardless of the underlying cause, the data collected from RingCentral's global survey of 2,000 knowledge workers sheds some new light on the daily work of professionals in many industries.

The report defined communications apps as those used for phone calls, texts, web meetings, video conferencing, team messaging, and more. On average, most workers are using four apps total, but 20% are using six or more apps at work.

According to the report, 66% of those workers surveyed said they want a single communications platform, but 44% of executives said they were content with their current toolset. This disconnect could be costly, as 70% of frontline workers said managing their volume of communications was a challenge to getting their work done. Still, that could just be a sign that there is too much communication to begin with, and may not be alleviated by fewer apps.

"Today's workforce is under siege by a flood of communications apps. More than ever, our attention is scattered across a wide array of different apps and communications channels," RingCentral CMO Riadh Dridi said in a press release. "These apps are meant to bolster our productivity, but managing myriad apps is proving difficult—with serious repercussions for businesses."
