= How to automate your business: 3 critical steps 

Automation can cut costs and improve the customer experience, but only if CIOs make the right investments, according to Forrester Research.

By Alison DeNisco Rayome | April 11, 2018, 6:04 AM PST 

 * More than half of firms are currently undergoing digital transformation to better serve customers. — Forrester, 2018
 * CIOs should use automation to digitize and optimize operations, to create and act upon advanced insights, and to drive business technology innovation. — Forrester, 2018

Automation technologies like artificial intelligence (AI), robotic process automation (RPA), and physical robots offer CIOs the opportunity to help their organization rethink its business model and improve the customer experience. These tools have the potential to both cut costs and reshape the customer experience, according to a Monday report from Forrester.

However, automation efforts can only succeed if CIOs make the right investments, the report noted. With more than half of all firms undergoing digital transformation efforts, CIOs must act as strategic partners for the rest of the C-suite in determining where automation fits in. 

Here are the three business goals that investments in automation must help drive, according to the report. 

== 1. Digitize and optimize operations 

Automation has the potential to dramatically reshape operations, including those in technology, finance, and manufacturing, the report noted.

"Business processes are essentially algorithms, and the more formalized the process, the easier it will be to hand that workflow off to machines," according to the report. "CIOs must move many of these business processes from manual and/or analog to digital and automated."

Examples of this include automating the maintenance and operation of the technology organization, systems, and equipment, to drive productivity with fewer costs. Companies may also invest in predictive maintenance, to help customers preempt equipment failure. They can also use automation to enable a DevOps workflow, and improve cybersecurity by using machine learning to detect anomalies and predict future threats. 

== 2. Create and act upon advanced insights 

Businesses driven by insights have a major competitive advantage in the marketplace, according to the report. "These customer-obsessed firms systematically harness insights across their organization and implement them to create competitive advantage using software," the report said. "CIOs can create differentiation, improve customer relevance, and increase top-line revenue by pursuing excellence in insights."

One example of this would be solving problems with big data. AI is critical for drawing actionable insights out of large data sets, the report noted, and will increasingly power the full automation sense-and-adapt phases of technology cycle to help businesses gain more valuable information.

Automation is also increasingly helping CIOs bring the power of digital to physical problems, the report said. For example, companies are already using automated vision systems that better detect faults in production. These technologies can also augment the performance of human employees as they serve customers, by providing insights and answers to employees when they need them.

== 3. Drive business technology innovation 

According to the report, "CIOs must drive business technology — the technology, systems, and processes to win, serve, and retain customers — to help their customer-obsessed organizations succeed in the marketplace." Automation technologies are playing an increasingly important role in making business technology more innovative, the report said.

In the best cases, automation can help companies create brand new business models, according to the report—for example, Robin Technologies deploys robotic lawnmowers that allow landscapers to focus on higher-margin tasks like design and irrigation systems.

Automation can also better match supply with demand, such as matching job candidates to potential employers, as Fiverr does for the gig economy. In other cases, automation can enable dynamic pricing to better target customers at different stages of their work with your company, the report said. 

= 6 tips to help your organization find potential employees 

Promote open positions, convey your organization's culture, and streamline the hiring process with these six tactics and Google tools.

By Andy Wolber | April 11, 2018, 11:37 AM PST 

 Some organizations rely on dedicated professionals—executive search firms, recruiters, human resources staff, or talent scouts—to handle the hiring process. Search professionals may work with you to clarify your organization's needs, define the necessary skills, craft a compelling job description, promote the position, connect you with candidates, or help you negotiate an employment agreement.

But in many enterprises, hiring remains a part-time task. The following six tactics and tools may help your organization more efficiently find people to fill open positions.

== 1. Post to a consistent place with Google Domains 

Give job seekers a single link to available jobs that they can bookmark, favorite, or save. For example, a page, such as exampleorganization.com/jobs, or a third-level domain, such as jobs.exampleorganization.com. Your CMS will likely let you create a "jobs" page within your website. You might then forward the jobs.exampleorganization.com domain to the jobs page on your website.

To do this within Google Domains, look at the list of your domains, select the icon in the row of your domain below the DNS column, scroll to the "Synthetic records" section, put jobs in the field with "Subdomain" in it, then paste the link to your jobs page into the area with "Destination URL" in it, select the "Permanent redirect" button, then select "Add."

Or you could forward to an external, third-party job listing service or site where you post open positions.

{{https://tr4.cbsistatic.com/hub/i/r/2018/04/11/1c2ff36b-4de9-4dea-90f9-f8d52b6704d6/resize/770x/467e31cdab038841b50cd68c69ca2bee/a-domainpointtojobs.jpg|Google Domains shows how you might create a permanent redirect of a third-level domain, such as jobs.exampleorganization.com to a jobs page on your website.}}

== 2. Support search in Google Jobs 

Type the term "jobs" in a Google search and you'll see a list of open positions, along with a few options a job-seeker may select to narrow your search. The displayed options at jobs.google.com rely on data associated with open positions, such as whether a position is full or part time, pay range, location, type of job, and so on.

If you use a listing service that supports Google Jobs, positions you've posted should appear within a Google Jobs search automatically. You may also follow the developer guidelines to add meta-data to the page for the job description on your website. A plug-in, such as the Jobs for WordPress plugin by BlueGlass, helps you capture the correct descriptive data for jobs on a WordPress site.

{{https://tr4.cbsistatic.com/hub/i/r/2018/04/11/145dfa1c-ac2d-47f0-a459-cc635d9ace33/resize/770x/fdf83420155e8aab93ea80c99aacf1ad/b-jobmetadata.jpg|Use the JobPosting schema as a guide when you create job description forms and processes. The items shown allow people to filter opportunities shown on job sites.}}

== 3. Share to your internal/external networks 

Share the job opening link to internal networks such as Google+, Slack, Hangouts Chat, or Microsoft Teams, and to external networks such as Facebook, Twitter, and LinkedIn. A "Come join me" post shared by a current employee to their networks can help raise awareness of opportunities.

== 4. Track traffic with Google Analytics 

Connect Google Analytics to your website then watch how people arrive on your jobs page, and which pages people view after they explore an opportunity. If lots of people view your organization's history and leadership team and then leave, that's a sign you need to fix tip number five.

== 5. Convey company culture 

Take a look at your staff and board leadership web pages. What does the page convey about your organization? Some organizations provide lists with names and positions. Other organizations add biographic profiles, photos, and contact information. Some staff pages even include links to presentations, code, projects, posts and articles to give prospective employees a window into each individual's public personality.

Videos that show people in your organization may also help a candidate grasp your organization's culture. While professionally produced videos accurately represent some companies, individually captured smartphone conversations or presentations offer an alternative approach. For example, see the "Working at Automattic" videos on YouTube from the folks behind WordPress.

== 6. Streamline selection with Google Hire 

Finally, if you have a significant number of positions available, consider subscribing to software that can help with the hiring process. Google Hire does this for organizations that use G Suite. Many other alternatives, such as Zoho Recruit, BambooHR, or recruiterbox also help with applicant tracking processes and can be found in the G Suite Marketplace.

Even if your organization lacks a full-time hiring professional, the above tactics will help improve your company's ability to promote openings and convey the personalities of people already on your team.

= 5 tips for managing shadow IT without destroying innovation 

Citizen development is a growing trend in many companies. Here's how IT departments can maintain security while letting users create their own business solutions.

By Mary Shacklett | April 16, 2018, 11:35 AM PST 

In the past, I have suggested ways to minimize shadow IT through active vendor and project management. But consumerization of IT has expanded to the point where many IT departments no longer know how many apps are running in the organization. According an article on cybersecurity site Dark Reading, CIOs report that shadow apps used within their companies can often number in the hundreds.

There are reasons why shadow IT has flourished.

One is that IT application request logs are too long. Given the rapid pace of business, users can't afford to wait.

Another is that users don't want to deal with IT because the department is perceived as overly controlling and its professionals are perceived as condescending, particularly when they use jargon that's unfamiliar to people without a tech background.

"The downsides of Shadow IT are well documented," said Lumagate CTO Stefan Scorling, in a blog post. "First, it can cause severe security issues, due to unsupported and unverified technology being used in the company as users bypass standard IT security procedures. Second, if an employee stores sensitive data on a personal Dropbox or Google Drive account, the threat of violating compliance and data protection policies is omnipresent."

This, of course, is the IT point of view. It doesn't mean much to users who have no direct accountability for governance, security—or whether the apps they develop or subscribe to work with other applications and systems in the company.

Moreover, once dotted lines on contracts are signed with vendors, users don't have much interest in managing vendor relationships, either.

Consequently, the growth and sustenance of shadow IT is a quandary for users, for IT and for the CEO. At the end of the day, it is also true that the only lens through which to view these challenges and concerns is through the lens of the company itself, and what the company needs to be successful.

Most corporate CEOs would likely say this:

The business needs to be agile, innovative and responsive to ever-changing business conditions to overcome the competition;

Users are in the best position to understand business needs, and if they can develop apps, great;

Concurrently, companies can't afford to overlook governance, security, data safekeeping and technology spend. A central business unit needs to do this, and the core competency for the task clearly rests in IT.

How do companies bring these seemingly conflicting forces together?

Aside from issuing directives, CEOs can't do this—so they turn to their most centralized source when it comes to overall knowledge and administration of technology—IT.

This reliance on IT comes with new stipulations, because today's companies and CEOs don't want IT to dominate application development if users are doing or sponsoring it. Instead, they want IT to facilitate it by ensuring that apps are safe, reliable and able to work with other apps.

How do CIOs and IT managers learn to walk this new line for shadow IT?

== 1. Embrace end user innovation—don't discourage it 

End users are becoming more comfortable developing apps without the knowledge and assistance of IT. This can strike fear into the hearts of CIOs, who are ultimately responsible for security and governance. But on the flip side, end users know the business and app needs best. With the aid of user-friendly app development tools, users can likely bring new apps to market faster. What's not to like about this new paradigm—provided the appropriate governance, security and app reliability are there?

== 2. Publish application guidelines for end user app developers 

One way CIOs can encourage end user development is by publishing a set of guidelines that address elements such as governance and security. The guide can include an IT help line to answer questions. This guide does three things: 1) it establishes a cooperative relationship between end business app developers and IT; 2) it educates end users on important governance and security standards; and 3) it gives IT and the company better knowledge about how many apps are being built so they can be logged into a central IT asset portfolio and tracked.

== 3. Manage the corporate app portfolio 

IT is best suited to manage the company's overall app portfolio. This portfolio should include every app—whether it is developed in IT or by an end user. Annually, an internal IT auditor or librarian should check the network log to review resident apps and to cross-check them against the IT asset management system to ensure that the two match. If there are discrepancies, the IT or the end business area that authored the app should be visited to acquire any additional information needed for the app, and to stress future compliance with a policy that requires new apps to be reported to IT for entry into the asset management system at the time they are developed.

== 4. Be hard-nosed on governance and security — when you have to 

As news continues to pour in about data and security breaches, no company concerned about its brand or reputation can afford to take shortcuts on security and governance of apps and data. Shadow IT is an obvious risk—and IT department has every right to take a hard line on breaches of protocol. However, there is also room for temperance. For instance, many end user apps and reports are built within the framework of a third party software that has comprehensive governance and security standards in place. An example is a commercial CRM package that provides users with easy ways to build dashboards. These are apps IT doesn't need to police.

== 5. Accept vendor management responsibilities 

End business users are notorious for signing up with vendors, and then forgetting about the vendor agreements that they signed. Focused on the business, they are more than happy to cede these vendor relationships to IT, which can worry about compliance with SLAs. Many CIOs don't appreciate this, given that they had no role in vetting and signing with the vendors in the first place. This is something CIOs should get over—because no department in the company manages tech vendor relationships more effectively than IT.

= 6 ways to increase buy-in from project stakeholders 

Gaining trust and cooperation from a project team is imperative for success. Here are some ways to improve communication with stakeholders and make sure they feel like an important part of a team.

By Moira Alexander | April 12, 2018, 6:24 AM PST 

Buy-in can be a difficult thing to quantify, especially within various stakeholder categories. Without full buy-in from team members, sponsors and other stakeholders, projects may seem to be progressing smoothly and then suddenly take a sharp turn for the worst, risking the final deliverables and customer satisfaction. Depending on the reasons for the change, this can pose significant challenges for project managers when trying to get things back on track. Here are six ways to increase stakeholder buy-in through each stage of a project and smooth a path towards success.

== 1. Identify what motivates stakeholders 

If you can gain an understanding of what motivates each stakeholder, it can become much easier to get a larger share of stakeholder buy-in. This may seem time-consuming up front but can help significantly maintain buy-in as a project progresses. Within the same company, individuals and teams may be motivated by completely different things. Teams may be motivated by financial rewards like bonuses or raises or performance benchmarks, while individuals may be motivated by work-life balance or opportunities for career growth. A key to being able to establish higher degrees of buy-in is in establishing the link between project and company goals and stakeholder values and motivations. This does not need to be a secret mission, but instead a direct dialogue with stakeholders to help identify and establish the linkage. It's important to note that it may not always be possible to meet all the factors that motivate stakeholders.

== 2. Focus on telling the truth, even when it isn't what stakeholders want to hear 

Building a culture of trust is vital if you expect stakeholders to buy into a project and execute tasks to the best of their abilities. Overall, environmental factors such as low morale, negative culture, and lack of trust could make stakeholders believe their contribution isn't valuable. If stakeholders feel there is a disconnect with a project manager, sponsor, team, functional unit, customer, or the company, they are likely to have a deep sense of distrust.

Get serious about the impact of this issue - it can have the power to ruin projects quickly. Be transparent about any issues that may be of concern and solicit feedback from key stakeholders. Avoid offering solutions that you are unsure you can deliver on. Rather, say, "I don't know, but I will look into that and let you know." Most stakeholders will be more trusting of you if you tell them the truth even if the answer isn't what they prefer. Be honest about issues and remain objective about solutions as this too can help to establish trusting relationships and increase buy-in.

== 3. Make sure stakeholders understand their contribution to a project 

Once you've been able to identify individual stakeholder motivations and focus on gaining their trust, drawing a direct line between what motivates them and project goals becomes much simpler. Determine how project goals benefit stakeholders and communicate this, allowing stakeholders to share their concerns and ideas. It is much easier to solidify buy-in if stakeholders fully understand how their contributions impact a project and how the project outcome impacts them in return. When the lines are blurred, it can create confusion and reduced interest, make sure you are able to clearly define their direct role and the project goals in relation to the other.

== 4. Reaffirm goals and communicate progress throughout execution 

It's not enough to set goals and establish a linkage between stakeholder performance at the beginning of a project. Throughout execution, project managers should ensure they reaffirm goals and update stakeholders on the progress. This information is useful in ensuring stakeholders are engaged from the beginning of a project to close. Often once a project is being executed, it becomes assumed that stakeholders understand their role and can remain focused on deliverables. This assumption can easily become a pitfall that derails a project. It's important to remind stakeholders about project goals and their role in reaching those goals throughout the project to avoid decreased buy-in.

== 5. Remain consistent 

Make sure to remain consistent in what you say and how often you communicate. As the project leader, your responsibility is to provide guidance and consistency throughout every stage of the project. Stakeholders need to know you are always there, always approachable, and consistent. This provides stakeholders with the much-needed stability necessary to remain vested.

== 6. Provide positive feedback after the project ends 

It isn't enough to only provide feedback on lessons learned at the end of a project. If you simply offer feedback around needed improvements, you are unlikely to re-establish trust or gain buy-in on the next project. Once a project has wrapped up, remember to thank your team and other stakeholders for their contributions and commitment; also, provide positive feedback about how stakeholder activities may have helped throughout project execution. This last step is simply considered good leadership.