= The 12 habits of highly collaborative organizations

* By Guest Contributor
* March 18, 2013, 6:12 AM PDT
* Takeaway: Here are twelve collaboration patterns or “principles” that successful organizations follow.

Did you know that there are more possible moves in a game of chess then there are atoms in the entire universe and seconds that have elapsed since the big bang? In fact, chess can be a virtually endless game. If that’s the case then how do chess masters emerge? What’s the point of trying to study something if the moves are endless? Any good chess player will tell you that one of the keys to success is the ability to recognize patterns and situations to help you identify what the best next move is.

When looking at collaboration and the future of work, the same logic applies. Every company is unique and no two collaboration initiatives are the same. However, after working with, speaking with and researching hundreds of companies (such as Wells Fargo, Unisys, Lowe’s, IBM, EA, The U.S. Government, TELUS, Intuit, Shell, and many others) my team at Chess Media Group and I have identified twelve collaboration patterns or “principles” that the successful organizations follow. Below you will find a visual highlighting these principles followed by a more in-depth description of each one.

== 1. Individual benefit is just as important as the overall corporate benefit (if not more important)

Don’t focus on the overall corporate value and benefit when communicating collaboration to employees. Employees care about how this will impact them on an individual basis. How will this make their jobs and lives easier?

== 2. Strategy before technology

Before rushing to pick that shiny new collaboration platform focus on developing a strategy which will help you understand the “why” before the “how.” This is crucial for the success of any collaboration initiative. You don’t want to be in a position where you have deployed a technology without understanding why. This can become a very costly mistake later.

== 3. Listen to the voice of the employee

We are always so adamant about listening to the voice of the customer, what about the voice of the employee? When going down the collaboration road within your enterprise it’s important to make employees a part of the decision making process from step one. Listen to their ideas, their needs, and their suggestions and integrate their feedback in your technology and strategy.

== 4. Learn to get out of the way

This is something Andrew McAfee (author of Enterprise 2.0 and co-author of Race Against the Machine) talks about quite frequently. Learn to empower and support your employees and then get out of their way. By trying to enforce and police everything you stifle collaboration within your organization. Some best practices and guidelines are fine to have but let your employees do what they need to do. Managers need to learn to follow from the front.

== 5. Lead by example

If leaders at your organization don’t use and support collaborative tools and strategies then why should the employees? Leaders are very powerful instruments to facilitate change and encourage desired behaviors. They must be visibly on board and this goes beyond just funding.

== 6. Integrate into the flow of work

Collaboration should never be seen as an additional task or requirement for employees. Instead collaboration should fit naturally into their flow of work. For example instead of having employees use multiple usernames, passwords, and log-in sites; create a “front-door” to the enterprise accessed through your collaboration platform.

== 7. Create a supportive environment

If your organization focuses on rewarding employees for individual performance as the main driver of success then it will become quite hard to encourage employees to share and communicate with each other. Why would they want to? We this quite often in financial services firms who promote employees to managerial roles such as VPs (and higher) simply because they brought in a lot of money. There is nothing wrong with rewarding employees for great performance but it’s also crucial to reward and recognize teamwork and collaboration. For example organizations can make a percentage of an employee’s bonus tied to how well they collaborate with their co-workers (some large enterprises are starting to experiment with this). A supportive environment also means having training and education resources available for employees as well as evangelists within the organization.

== 8. Measure what matters

There are a lot of things that an organization can measure but that doesn’t mean that all of these things should be measured. Focus on the metrics that matter to your organization and the ones that are tied back to a business case. Some organizations focus on “busy” metrics such as comments submitted or groups created. Others focus on metrics such as engagement (defined as how connected and passionate an employee feels about the company and the work they do).

== 9. Persistence

I believe that collaborative initiatives shouldn’t be pilots they should be corporate initiatives. These efforts can certainly take time but if the organization makes the decision that collaboration is the direction they want to go down then that’s it. No giving up and no turning back. Moving forward, organizations cannot succeed without connecting their employees and their information. Making collaboration work isn’t an option it’s THE option. 

== 10. Adapt and evolve

It’s important to remember that collaboration is perpetual. It’s a never ending evolution as new tools and strategies for the workplace continue to emerge. This means that it’s important for your organization to be able to adapt and evolve as things change. Keep a pulse on what’s going on in the industry and inside of your organization. This will allow you to innovate and anticipate.

== 11. Employee collaboration also benefits the customer

While customer collaboration and employee collaboration do solve very different and unique problems, employee collaboration has tremendous value to your customers. Employees are able to provide a better experience and superior support by being able to tap into internal experts, information, and resources which can be used to help customers. Consider a customer that is working with a support representative who unfortunately does not know how to solve the customer’s problem. The employee however has access to the entire organization to find the right information and share it with the customer. 

== 12. Collaboration can make the world a better place

Perhaps the most important principle of collaboration is that it can make the world a better place. Sure, collaboration can make our employee more productive and benefit our customers. But collaboration also allows employees to feel more connected to their jobs and co-workers, reduces stress at the workplace, makes their jobs easier, allows for more work freedom, and in general makes them happier people. This means less stress at home, less arguments with spouses, and more time to spend with loved ones. Collaboration not only positively impacts the lives of employees at work but also at home.

*Jacob Morgan is the principal of Chess Media Group, a management consulting and strategic advisory firm on collaboration. Jacob is also the author of the Amazon best-selling book, The Collaborative Organization, which is the first comprehensive strategy guide to emergent workplace collaboration. He can be found on Twitter @JacobM.*