{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_health_status)" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_mon_quorum_status)" }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_pool_max_avail)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"ceph\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"ceph\"}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"ceph\"}/ceph_cluster_total_bytes{job=\"ceph\"}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_in{job=\"ceph\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{job=\"ceph\"})-count(ceph_osd_in{job=\"ceph\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_up)-count(ceph_osd_metadata)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{job=\"ceph\"})"
    }
   ]
  },
  {
   "title": "Agerage OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"ceph\"}/1000)"
    }
   ]
  },
  {
   "title": "Agerage OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"ceph\"}/1000)"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_monitor_latency_seconds)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{job=\"ceph\"}-ceph_cluster_total_used_bytes{job=\"ceph\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"ceph\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_cluster_total_bytes{job=\"ceph\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(rate(ceph_osd_op_w[30s]))", "legendFormat": "Write" },
    { "expr": "sum(rate(ceph_osd_op_r[30s]))", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w_in_bytes[30s]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r_out_bytes[30s]))",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_cluster_total_objects", "legendFormat": "Total" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_misplaced_objects", "legendFormat": "Misplaced" }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_total", "legendFormat": "Total" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_total - ceph_pg_clean", "legendFormat": "Unclean" }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_stuck_degraded_pgs", "legendFormat": "Degraded" },
    { "expr": "ceph_stuck_stale_pgs", "legendFormat": "Stale" },
    { "expr": "ceph_stuck_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_stuck_undersized_pgs", "legendFormat": "Undersized" }
   ]
  },
  { "title": "Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_recovery_ops[30s]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_keys", "legendFormat": "Keys" }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_objects", "legendFormat": "Objects" }
   ]
  }
 ]
}